# Generated by Django 4.1.7 on 2023-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dispositivo', models.CharField(max_length=100, verbose_name='Nombre del Dispositivo')),
                ('codigo_dispositivo', models.CharField(max_length=20, verbose_name='Codigo del Dispositivo')),
                ('modelo_dispositivo', models.CharField(max_length=20, verbose_name='Modelo del Dispositivo')),
                ('tempmin_dispositivo', models.IntegerField(verbose_name='Temperatura Minima')),
                ('tempmax_dispositivo', models.IntegerField(verbose_name='Temperatura Maxima')),
                ('estado_dispositivo', models.BooleanField(default=1, verbose_name='Estado Dispositivos')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
