# Generated by Django 4.1.7 on 2023-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='estadovent_dispositivo',
            field=models.BooleanField(default=1, verbose_name='Estado del Ventilador del dispositivo'),
        ),
    ]
