# Generated by Django 4.1.7 on 2023-03-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_dispositivos_estadovent_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivos',
            name='estado_dispositivo',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='modo_dispositivo',
            field=models.BooleanField(default=1, verbose_name='Modo Automatico'),
        ),
    ]
