# Generated by Django 4.1.7 on 2023-03-16 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paises',
            name='sigla_pais',
            field=models.CharField(default=2, max_length=2, verbose_name='Sigla del Pais'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
                ('codigo_departamento', models.CharField(max_length=2, verbose_name='Codigo del Departamento')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Paiz', to='regiones.paises')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
